/**
 * Role Permissions Matrix
 * Must match Master Spec Section 4.8 (Permissions Matrix)
 */

export const ROLE_PERMISSIONS = {
  ADMIN: {
    'case.create': true,
    'case.read': true,
    'case.update': true,
    'case.delete': true,
    'case.close': true,
    'client.create': true,
    'client.read': true,
    'client.update': true,
    'client.delete': true,
    'doc.metadata.view': true,
    'doc.content.view': true,
    'doc.upload': true,
    'doc.delete': true,
    'ai.metadata.view': true,
    'ai.results.view': true,
    'ai.ask': true,
    'ai.draft': true,
    'task.create': true,
    'task.assign': true,
    'task.complete': true,
    'audit.view': true,
    'admin.manage_users': true,
    'admin.manage_plan': true,
    'billing.manage': true,
  },
  LAWYER: {
    'case.create': true,
    'case.read': true,
    'case.update': true,
    'case.delete': true,
    'case.close': true,
    'client.create': true,
    'client.read': true,
    'client.update': true,
    'client.delete': true,
    'doc.metadata.view': true,
    'doc.content.view': true,
    'doc.upload': true,
    'doc.delete': false,
    'ai.metadata.view': true,
    'ai.results.view': true,
    'ai.ask': true,
    'ai.draft': true,
    'task.create': true,
    'task.assign': true,
    'task.complete': true,
    'audit.view': true,
    'admin.manage_users': false,
    'admin.manage_plan': false,
    'billing.manage': false,
  },
  PARALEGAL: {
    'case.create': false,
    'case.read': true,
    'case.update': true,
    'case.delete': false,
    'case.close': false,
    'client.create': true,
    'client.read': true,
    'client.update': true,
    'client.delete': false,
    'doc.metadata.view': true,
    'doc.content.view': true,
    'doc.upload': true,
    'doc.delete': false,
    'ai.metadata.view': true,
    'ai.results.view': true,
    'ai.ask': true,
    'ai.draft': true,
    'task.create': true,
    'task.assign': true,
    'task.complete': true,
    'audit.view': true,
    'admin.manage_users': false,
    'admin.manage_plan': false,
    'billing.manage': false,
  },
  VIEWER: {
    'case.create': false,
    'case.read': true,
    'case.update': false,
    'case.delete': false,
    'case.close': false,
    'client.create': false,
    'client.read': true,
    'client.update': false,
    'client.delete': false,
    'doc.metadata.view': true,
    'doc.content.view': true,
    'doc.upload': false,
    'doc.delete': false,
    'ai.metadata.view': true,
    'ai.results.view': true,
    'ai.ask': false,
    'ai.draft': false,
    'task.create': false,
    'task.assign': false,
    'task.complete': false,
    'audit.view': true,
    'admin.manage_users': false,
    'admin.manage_plan': false,
    'billing.manage': false,
  },
} as const;

export type Role = keyof typeof ROLE_PERMISSIONS;
export type PermissionKey = keyof typeof ROLE_PERMISSIONS['ADMIN'];
